export const FETCH_COURSES_REQUEST = 'FETCH_COURSES_REQUEST';
export const FETCH_COURSES_SUCCESS = 'FETCH_COURSES_SUCCESS';
export const FETCH_COURSES_FAILURE = 'FETCH_COURSES_FAILURE';

export const DELETE_COURSES_REQUEST = 'DELETE_COURSES_REQUEST';
export const DELETE_COURSES_SUCCESS = 'DELETE_COURSES_SUCCESS';
export const DELETE_COURSES_FAILURE = 'DELETE_COURSES_FAILURE';

export const CREATE_COURSE_REQUEST = 'CREATE_COURSE_REQUEST';
export const CREATE_COURSE_SUCCESS = 'CREATE_COURSE_SUCCESS';
export const CREATE_COURSE_FAILURE = 'CREATE_COURSE_FAILURE';
